packages:
- location: .
- location: https://github.com/sheepforce/Haskell_Data.Chemistry/archive/cb3634f33aac667bcbf85a2f3095c0f2cf8d0c60.zip
  extra-dep: true

extra-deps:
- HChem-libs-0.2

resolver: lts-9.14
